// <auto-generated />
using System;
using EngineController.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EngineController.Migrations
{
    [DbContext(typeof(EngineControllerContext))]
    [Migration("20210710234928_AddedRegisteredVMs")]
    partial class AddedRegisteredVMs
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("EngineController.Models.AppliedCompetitionPenalty", b =>
                {
                    b.Property<int>("CompetitionPenaltyID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("VmId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AppliedVirtualMachineVmId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TeamID1")
                        .HasColumnType("INTEGER");

                    b.HasKey("CompetitionPenaltyID", "TeamID", "VmId");

                    b.HasIndex("AppliedVirtualMachineVmId");

                    b.HasIndex("TeamID");

                    b.HasIndex("TeamID1");

                    b.HasIndex("VmId");

                    b.ToTable("AppliedCompetitionPenalties");
                });

            modelBuilder.Entity("EngineController.Models.CompetitionPenalty", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PenaltyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PenaltyScript")
                        .HasColumnType("TEXT");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScriptType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SystemIdentifier")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("SystemIdentifier");

                    b.ToTable("CompetitionPenalties");
                });

            modelBuilder.Entity("EngineController.Models.CompetitionSystem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReadmeText")
                        .HasColumnType("TEXT");

                    b.Property<string>("SystemIdentifier")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("CompetitionSystem");
                });

            modelBuilder.Entity("EngineController.Models.CompetitionTask", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScriptType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SystemIdentifier")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TaskName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValidationScript")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("SystemIdentifier");

                    b.ToTable("CompetitionTasks");
                });

            modelBuilder.Entity("EngineController.Models.CompletedCompetitionTask", b =>
                {
                    b.Property<int>("CompetitionTaskID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamID")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("VmId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AppliedVirtualMachineVmId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TeamID1")
                        .HasColumnType("INTEGER");

                    b.HasKey("CompetitionTaskID", "TeamID", "VmId");

                    b.HasIndex("AppliedVirtualMachineVmId");

                    b.HasIndex("TeamID");

                    b.HasIndex("TeamID1");

                    b.HasIndex("VmId");

                    b.ToTable("CompletedCompetitionTasks");
                });

            modelBuilder.Entity("EngineController.Models.RegisteredVirtualMachine", b =>
                {
                    b.Property<Guid>("VmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsConnectedNow")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastCheckIn")
                        .HasColumnType("TEXT");

                    b.Property<int>("SystemIdentifier")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TeamID1")
                        .HasColumnType("INTEGER");

                    b.HasKey("VmId");

                    b.HasIndex("SystemIdentifier");

                    b.HasIndex("TeamID");

                    b.HasIndex("TeamID1");

                    b.ToTable("RegisteredVirtualMachines");
                });

            modelBuilder.Entity("EngineController.Models.Team", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("EngineController.Models.AppliedCompetitionPenalty", b =>
                {
                    b.HasOne("EngineController.Models.RegisteredVirtualMachine", "AppliedVirtualMachine")
                        .WithMany()
                        .HasForeignKey("AppliedVirtualMachineVmId");

                    b.HasOne("EngineController.Models.CompetitionPenalty", "CompetitionPenalty")
                        .WithMany()
                        .HasForeignKey("CompetitionPenaltyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EngineController.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EngineController.Models.Team", null)
                        .WithMany("AppliedCompetitionPenalties")
                        .HasForeignKey("TeamID1");

                    b.HasOne("EngineController.Models.RegisteredVirtualMachine", null)
                        .WithMany("CompetitionPenalties")
                        .HasForeignKey("VmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppliedVirtualMachine");

                    b.Navigation("CompetitionPenalty");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("EngineController.Models.CompetitionPenalty", b =>
                {
                    b.HasOne("EngineController.Models.CompetitionSystem", null)
                        .WithMany("CompetitionPenalties")
                        .HasForeignKey("SystemIdentifier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EngineController.Models.CompetitionTask", b =>
                {
                    b.HasOne("EngineController.Models.CompetitionSystem", null)
                        .WithMany("CompetitionTasks")
                        .HasForeignKey("SystemIdentifier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EngineController.Models.CompletedCompetitionTask", b =>
                {
                    b.HasOne("EngineController.Models.RegisteredVirtualMachine", "AppliedVirtualMachine")
                        .WithMany()
                        .HasForeignKey("AppliedVirtualMachineVmId");

                    b.HasOne("EngineController.Models.CompetitionTask", "CompetitionTask")
                        .WithMany()
                        .HasForeignKey("CompetitionTaskID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EngineController.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EngineController.Models.Team", null)
                        .WithMany("CompletedCompetitionTasks")
                        .HasForeignKey("TeamID1");

                    b.HasOne("EngineController.Models.RegisteredVirtualMachine", null)
                        .WithMany("CompetitionTasks")
                        .HasForeignKey("VmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppliedVirtualMachine");

                    b.Navigation("CompetitionTask");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("EngineController.Models.RegisteredVirtualMachine", b =>
                {
                    b.HasOne("EngineController.Models.CompetitionSystem", "CompetitionSystem")
                        .WithMany()
                        .HasForeignKey("SystemIdentifier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EngineController.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EngineController.Models.Team", null)
                        .WithMany("RegisteredVirtualMachines")
                        .HasForeignKey("TeamID1");

                    b.Navigation("CompetitionSystem");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("EngineController.Models.CompetitionSystem", b =>
                {
                    b.Navigation("CompetitionPenalties");

                    b.Navigation("CompetitionTasks");
                });

            modelBuilder.Entity("EngineController.Models.RegisteredVirtualMachine", b =>
                {
                    b.Navigation("CompetitionPenalties");

                    b.Navigation("CompetitionTasks");
                });

            modelBuilder.Entity("EngineController.Models.Team", b =>
                {
                    b.Navigation("AppliedCompetitionPenalties");

                    b.Navigation("CompletedCompetitionTasks");

                    b.Navigation("RegisteredVirtualMachines");
                });
#pragma warning restore 612, 618
        }
    }
}
